version: "3"

services:
  portfolio2022:
    container_name: portfolio2022
    image: portfolio2022:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_ENVIRONMENT=${PROJECT_ENVIRONMENT}
        - PGHOST=${PGHOST}
        - PGDATABASE=${PGDATABASE}
        - PGUSER=${PGUSER}
        - PGPASSWORD=${PGPASSWORD}
        - PGPORT=${PGPORT}
        - DATABASE_URL=${DATABASE_URL}
        - DISCORD_TOKEN=${DISCORD_TOKEN}
        - DISCORD_USER_ID=${DISCORD_USER_ID}
    restart: on-failure
    networks:
      - hosted
      - postgres
    #ports:
    #- "2260:3001"

networks:
  hosted:
    external: true
  postgres:
    external: true
