version: "3"

services:
  portfolio2022:
    container_name: portfolio2022
    image: portfolio2022:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - hosted
      - postgres
    #ports:
    #- "2260:3001"

networks:
  hosted:
    external: true
  postgres:
    external: true
